### Yellow Taxi Trip Records

In [1]:
#Importar librerías
import pickle
import pandas as pd

In [11]:
#Leer diccionario con vínculos
diccionario = pd.read_pickle('datos_tlc/tlc_amarillos')

In [14]:
diccionario

{'yellow_2023_1': "yellow_2023_1 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet')",
 'yellow_2022_2': "yellow_2022_2 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-01.parquet')",
 'yellow_2022_3': "yellow_2022_3 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-02.parquet')",
 'yellow_2022_4': "yellow_2022_4 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-03.parquet')",
 'yellow_2022_5': "yellow_2022_5 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-04.parquet')",
 'yellow_2022_6': "yellow_2022_6 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-05.parquet')",
 'yellow_2022_7': "yellow_2022_7 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-06.parquet')",
 'yellow_2022_8': "yellow_2022_8 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet')",
 'yellow_2022_9': "yellow_2022_9 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-08.parquet')",
 'yellow_2022_10': "yellow_2022_10 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-09.parquet')",
 'yellow_2022_11': "yellow_2022_11 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-10.parquet')",
 'yellow_2022_12': "yellow_2022_12 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-11.parquet')",
 'yellow_2022_13': "yellow_2022_13 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-12.parquet')",
 'yellow_2021_14': "yellow_2021_14 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet')",
 'yellow_2021_15': "yellow_2021_15 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-02.parquet')",
 'yellow_2021_16': "yellow_2021_16 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-03.parquet')",
 'yellow_2021_17': "yellow_2021_17 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-04.parquet')",
 'yellow_2021_18': "yellow_2021_18 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-05.parquet')",
 'yellow_2021_19': "yellow_2021_19 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-06.parquet')",
 'yellow_2021_20': "yellow_2021_20 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-07.parquet')",
 'yellow_2021_21': "yellow_2021_21 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-08.parquet')",
 'yellow_2021_22': "yellow_2021_22 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-09.parquet')",
 'yellow_2021_23': "yellow_2021_23 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-10.parquet')",
 'yellow_2021_24': "yellow_2021_24 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-11.parquet')",
 'yellow_2021_25': "yellow_2021_25 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-12.parquet')",
 'yellow_2020_26': "yellow_2020_26 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-01.parquet')",
 'yellow_2020_27': "yellow_2020_27 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-02.parquet')",
 'yellow_2020_28': "yellow_2020_28 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-03.parquet')",
 'yellow_2020_29': "yellow_2020_29 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-04.parquet')",
 'yellow_2020_30': "yellow_2020_30 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-05.parquet')",
 'yellow_2020_31': "yellow_2020_31 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-06.parquet')",
 'yellow_2020_32': "yellow_2020_32 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-07.parquet')",
 'yellow_2020_33': "yellow_2020_33 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-08.parquet')",
 'yellow_2020_34': "yellow_2020_34 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-09.parquet')",
 'yellow_2020_35': "yellow_2020_35 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-10.parquet')",
 'yellow_2020_36': "yellow_2020_36 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-11.parquet')",
 'yellow_2020_37': "yellow_2020_37 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-12.parquet')",
 'yellow_2019_38': "yellow_2019_38 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-01.parquet')",
 'yellow_2019_39': "yellow_2019_39 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-02.parquet')",
 'yellow_2019_40': "yellow_2019_40 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-03.parquet')",
 'yellow_2019_41': "yellow_2019_41 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-04.parquet')",
 'yellow_2019_42': "yellow_2019_42 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-05.parquet')",
 'yellow_2019_43': "yellow_2019_43 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-06.parquet')",
 'yellow_2019_44': "yellow_2019_44 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-07.parquet')",
 'yellow_2019_45': "yellow_2019_45 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-08.parquet')",
 'yellow_2019_46': "yellow_2019_46 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-09.parquet')",
 'yellow_2019_47': "yellow_2019_47 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-10.parquet')",
 'yellow_2019_48': "yellow_2019_48 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-11.parquet')",
 'yellow_2019_49': "yellow_2019_49 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-12.parquet')",
 'yellow_2018_50': "yellow_2018_50 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-01.parquet')",
 'yellow_2018_51': "yellow_2018_51 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-02.parquet')",
 'yellow_2018_52': "yellow_2018_52 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-03.parquet')",
 'yellow_2018_53': "yellow_2018_53 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-04.parquet')",
 'yellow_2018_54': "yellow_2018_54 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-05.parquet')",
 'yellow_2018_55': "yellow_2018_55 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-06.parquet')",
 'yellow_2018_56': "yellow_2018_56 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-07.parquet')",
 'yellow_2018_57': "yellow_2018_57 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-08.parquet')",
 'yellow_2018_58': "yellow_2018_58 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-09.parquet')",
 'yellow_2018_59': "yellow_2018_59 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-10.parquet')",
 'yellow_2018_60': "yellow_2018_60 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-11.parquet')",
 'yellow_2018_61': "yellow_2018_61 = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-12.parquet')"}

In [15]:
#Descargar primer tabla (12/2018)
exec(diccionario['yellow_2018_61'])

In [17]:
#Ver primer tabla (12/2018)
yellow_2018_61.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8195675 entries, 0 to 8195674
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   object
 18  airport_fee            object
dtypes: datetime64[ns](2), float64(10), int64(4), object(3)
memory usage: 1.2+ GB

Considerar eliminar:
- VendorID (Código que indica el proveedor de datos)
- RateCodeID (Código de tarifa final en vigor al final del viaje)
- Store_and_fwd_flag (Indica si el registro del viaje se mantuvo en memoria del vehículo antes de enviarlo al proveedor)

In [18]:
yellow_2018_61

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2018-12-01 00:28:22,2018-12-01 00:44:07,2.0,2.50,1.0,N,148,234,1,12.00,0.50,0.5,3.95,0.00,0.3,17.25,None,None
1,1,2018-12-01 00:52:29,2018-12-01 01:11:37,3.0,2.30,1.0,N,170,144,1,13.00,0.50,0.5,2.85,0.00,0.3,17.15,None,None
2,2,2018-12-01 00:12:52,2018-12-01 00:36:23,1.0,0.00,1.0,N,113,193,2,2.50,0.50,0.5,0.00,0.00,0.3,3.80,None,None
3,1,2018-12-01 00:35:08,2018-12-01 00:43:11,1.0,3.90,1.0,N,95,92,1,12.50,0.50,0.5,2.75,0.00,0.3,16.55,None,None
4,1,2018-12-01 00:21:54,2018-12-01 01:15:13,1.0,12.80,1.0,N,163,228,1,45.00,0.50,0.5,9.25,0.00,0.3,55.55,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8195670,2,2018-12-31 23:25:00,2018-12-31 23:40:00,NaN,9.32,NaN,None,50,265,0,0.00,0.00,0.0,10.00,10.50,0.3,0.00,None,None
8195671,2,2018-12-31 23:04:00,2018-12-31 23:30:00,NaN,9.06,NaN,None,243,182,0,28.95,2.75,0.5,0.00,0.00,0.3,32.50,None,None
8195672,2,2018-12-31 23:02:00,2018-12-31 23:35:00,NaN,11.70,NaN,None,236,254,0,51.05,2.75,0.5,0.00,0.00,0.3,54.60,None,None
8195673,2,2018-12-31 23:17:00,2018-12-31 23:43:00,NaN,7.82,NaN,None,146,78,0,23.19,2.75,0.5,0.00,5.76,0.3,32.50,None,None
8195674,5,2018-12-31 23:01:26,2018-12-31 23:43:42,NaN,9.92,NaN,None,95,48,0,34.74,0.00,0.5,0.00,5.76,0.3,41.30,None,None

Separar:
- tpep_pickup_datetime
- tpep_dropoff_datetime

En día (DD-MM-YYYY)
Hora de pickup
Hora de dropoff

¿A qué se traducen PULocationID y DOLocationID?