In [6]:
import pandas as pd
import requests

In [3]:
df=pd.read_parquet("fhv_tripdata_2023-01.parquet")

In [10]:
# API

url = "https://data.cityofnewyork.us/resource/c3uy-2p5r.json"

# Parámetros de paginación
limit = 1000  # Número máximo de resultados por página
offset = 0    # Número de resultados a omitir antes de comenzar a obtener resultados
results = []  # Lista para almacenar los resultados

In [11]:

while True:
    # Construir la URL con los parámetros de paginación
    query_url = f'{url}?$limit={limit}&$offset={offset}'
    
    # Leer los datos de la URL en un DataFrame
    df = pd.read_json(query_url)
    
    # Agregar los resultados al DataFrame
    results.append(df)
    
    # Verificar si hay más resultados
    if len(df) < limit:
        break  # Si no hay más resultados, salir del ciclo
    
    offset += limit  # Incrementar el offset para la próxima página

# Concatenar todos los DataFrames en uno solo
df_final = pd.concat(results, ignore_index=True)

In [13]:
df_final

,unique_id,indicator_id,name,measure,measure_info,geo_type_name,geo_join_id,geo_place_name,time_period,start_date,data_value
0,216498,386,Ozone (O3),Mean,ppb,CD,313,Coney Island (CD13),Summer 2013,2013-06-01T00:00:00.000,34.64
1,216499,386,Ozone (O3),Mean,ppb,CD,313,Coney Island (CD13),Summer 2014,2014-06-01T00:00:00.000,33.22
2,219969,386,Ozone (O3),Mean,ppb,Borough,1,Bronx,Summer 2013,2013-06-01T00:00:00.000,31.25
3,219970,386,Ozone (O3),Mean,ppb,Borough,1,Bronx,Summer 2014,2014-06-01T00:00:00.000,31.15
4,164876,383,Sulfur Dioxide (SO2),Mean,ppb,CD,211,Morris Park and Bronxdale (CD11),Winter 2008-09,2008-12-01T00:00:00.000,5.89
...,...,...,...,...,...,...,...,...,...,...,...
16117,671118,386,Ozone (O3),Mean,ppb,CD,306,Park Slope and Carroll Gardens (CD6),Summer 2020,2020-06-01T00:00:00.000,28.70
16118,671119,386,Ozone (O3),Mean,ppb,CD,305,East New York and Starrett City (CD5),Summer 2020,2020-06-01T00:00:00.000,29.56
16119,671120,386,Ozone (O3),Mean,ppb,CD,304,Bushwick (CD4),Summer 2020,2020-06-01T00:00:00.000,29.65
16120,671121,386,Ozone (O3),Mean,ppb,CD,303,Bedford Stuyvesant (CD3),Summer 2020,2020-06-01T00:00:00.000,29.28
16121,671122,386,Ozone (O3),Mean,ppb,CD,302,Fort Greene and Brooklyn Heights (CD2),Summer 2020,2020-06-01T00:00:00.000,28.93

In [48]:
df_final[df_final['name'] == 'Traffic Density- Annual Vehicle Miles Traveled for Cars']

,unique_id,indicator_id,name,measure,measure_info,geo_type_name,geo_join_id,geo_place_name,time_period,start_date,data_value
1279,151671,644,Traffic Density- Annual Vehicle Miles Traveled...,million miles,per km2,UHF42,101,Kingsbridge - Riverdale,2005,2005-01-01T00:00:00.000,22.6
1280,151672,644,Traffic Density- Annual Vehicle Miles Traveled...,million miles,per km2,UHF42,102,Northeast Bronx,2005,2005-01-01T00:00:00.000,14.6
1281,151673,644,Traffic Density- Annual Vehicle Miles Traveled...,million miles,per km2,UHF42,103,Fordham - Bronx Pk,2005,2005-01-01T00:00:00.000,22.8
1282,151674,644,Traffic Density- Annual Vehicle Miles Traveled...,million miles,per km2,UHF42,104,Pelham - Throgs Neck,2005,2005-01-01T00:00:00.000,20.6
1283,151675,644,Traffic Density- Annual Vehicle Miles Traveled...,million miles,per km2,UHF42,105,Crotona -Tremont,2005,2005-01-01T00:00:00.000,36.3
...,...,...,...,...,...,...,...,...,...,...,...
8955,325402,644,Traffic Density- Annual Vehicle Miles Traveled...,million miles,per km2,CD,413,Queens Village (CD13),2016,2016-01-01T00:00:00.000,30.1
8956,325403,644,Traffic Density- Annual Vehicle Miles Traveled...,million miles,per km2,CD,414,Rockaway and Broad Channel (CD14),2016,2016-01-01T00:00:00.000,6.8
8957,325404,644,Traffic Density- Annual Vehicle Miles Traveled...,million miles,per km2,CD,501,St. George and Stapleton (CD1),2016,2016-01-01T00:00:00.000,10.7
8958,325405,644,Traffic Density- Annual Vehicle Miles Traveled...,million miles,per km2,CD,502,South Beach and Willowbrook (CD2),2016,2016-01-01T00:00:00.000,11.1
8959,325406,644,Traffic Density- Annual Vehicle Miles Traveled...,million miles,per km2,CD,503,Tottenville and Great Kills (CD3),2016,2016-01-01T00:00:00.000,6.3

In [15]:
df_final['name'].value_counts()

Fine Particulate Matter (PM2.5)                                                 5076
Nitrogen Dioxide (NO2)                                                          5076
Ozone (O3)                                                                      1692
Sulfur Dioxide (SO2)                                                            1128
PM2.5-Attributable Asthma Emergency Department Visits                            384
O3-Attributable Asthma Emergency Department Visits                               384
O3-Attributable Asthma Hospitalizations                                          384
Traffic Density- Annual Vehicle Miles Traveled for Cars                          214
Traffic Density- Annual Vehicle Miles Traveled                                   209
Traffic Density- Annual Vehicle Miles Traveled for Trucks                        209
PM2.5-Attributable Cardiovascular Hospitalizations (Adults 40 Yrs and Older)     192
O3-Attributable Cardiac and Respiratory Deaths                                   192
PM2.5-Attributable Deaths                                                        192
PM2.5-Attributable Respiratory Hospitalizations (Adults 20 Yrs and Older)        192
Air Toxics Concentrations- Average Benzene Concentrations                        155
Air Toxics Concentrations- Average Formaldehyde Concentrations                   155
Boiler Emissions- Total SO2 Emissions                                             96
Boiler Emissions- Total PM2.5 Emissions                                           96
Boiler Emissions- Total NOx Emissions                                             96
Name: name, dtype: int64

In [42]:
b=df_final['geo_place_name'].value_counts().index.tolist()
b

['Long Island City - Astoria',
 'West Queens',
 'East New York',
 'Bedford Stuyvesant - Crown Heights',
 'Downtown - Heights - Slope',
 'Greenpoint',
 'East Flatbush - Flatbush',
 'Canarsie - Flatlands',
 'Bensonhurst - Bay Ridge',
 'Pelham - Throgs Neck',
 'Fordham - Bronx Pk',
 'Northeast Bronx',
 'Kingsbridge - Riverdale',
 'Flushing - Clearview',
 'Borough Park',
 'Coney Island - Sheepshead Bay',
 'Ridgewood - Forest Hills',
 'Williamsburg - Bushwick',
 'Southwest Queens',
 'Jamaica',
 'Southeast Queens',
 'Rockaways',
 'Washington Heights',
 'Central Harlem - Morningside Heights',
 'East Harlem',
 'Upper West Side',
 'Sunset Park',
 'South Beach - Tottenville',
 'Union Square - Lower East Side',
 'Lower Manhattan',
 'Gramercy Park - Murray Hill',
 'Bayside - Little Neck',
 'Fresh Meadows',
 'Port Richmond',
 'Stapleton - St. George',
 'Willowbrook',
 'New York City',
 'Greenwich Village - SoHo',
 'Chelsea - Clinton',
 'Hunts Point - Mott Haven',
 'High Bridge - Morrisania',
 'Crotona -Tremont',
 'Upper East Side',
 'Staten Island',
 'Queens',
 'Manhattan',
 'Bronx',
 'Brooklyn',
 'East Flatbush (CD17)',
 'Woodside and Sunnyside (CD2)',
 'Long Island City and Astoria (CD1)',
 'Flatlands and Canarsie (CD18)',
 'Hunts Point and Longwood (CD2)',
 'Brownsville (CD16)',
 'Jackson Heights (CD3)',
 'Flatbush and Midwood (CD14)',
 'Borough Park (CD12)',
 'Bay Ridge and Dyker Heights (CD10)',
 'South Crown Heights and Lefferts Gardens (CD9)',
 'Fordham and University Heights (CD5)',
 'Highbridge and Concourse (CD4)',
 'Sheepshead Bay (CD15)',
 'Tottenville and Great Kills (CD3)',
 'Elmhurst and Corona (CD4)',
 'South Beach and Willowbrook (CD2)',
 'St. George and Stapleton (CD1)',
 'Rockaway and Broad Channel (CD14)',
 'Queens Village (CD13)',
 'Jamaica and Hollis (CD12)',
 'Bayside and Little Neck (CD11)',
 'Ridgewood and Maspeth (CD5)',
 'South Ozone Park and Howard Beach (CD10)',
 'Kew Gardens and Woodhaven (CD9)',
 'Hillcrest and Fresh Meadows (CD8)',
 'Flushing and Whitestone (CD7)',
 'Rego Park and Forest Hills (CD6)',
 'Morrisania and Crotona (CD3)',
 'Coney Island (CD13)',
 'Mott Haven and Melrose (CD1)',
 'Parkchester and Soundview (CD9)',
 'Morris Park and Bronxdale (CD11)',
 'Williamsbridge and Baychester (CD12)',
 'Greenpoint and Williamsburg (CD1)',
 'Fort Greene and Brooklyn Heights (CD2)',
 'Bedford Stuyvesant (CD3)',
 'Bushwick (CD4)',
 'East New York and Starrett City (CD5)',
 'Park Slope and Carroll Gardens (CD6)',
 'Sunset Park (CD7)',
 'Crown Heights and Prospect Heights (CD8)',
 'Washington Heights and Inwood (CD12)',
 'Kingsbridge Heights and Bedford (CD7)',
 'Riverdale and Fieldston (CD8)',
 'Belmont and East Tremont (CD6)',
 'Bensonhurst (CD11)',
 'Stuyvesant Town and Turtle Bay (CD6)',
 'East Harlem (CD11)',
 'Central Harlem (CD10)',
 'Throgs Neck and Co-op City (CD10)',
 'Upper East Side (CD8)',
 'Upper West Side (CD7)',
 'Morningside Heights and Hamilton Heights (CD9)',
 'Midtown (CD5)',
 'Clinton and Chelsea (CD4)',
 'Lower East Side and Chinatown (CD3)',
 'Greenwich Village and Soho (CD2)',
 'Financial District (CD1)',
 'Upper East Side-Gramercy',
 'Chelsea-Village',
 'Union Square-Lower Manhattan',
 'Bayside Little Neck-Fresh Meadows',
 'Northern SI',
 'Southern SI',
 'South Bronx']

In [39]:
a=a.reset_index()

In [41]:
a['index'].tolist()

['Long Island City - Astoria',
 'West Queens',
 'East New York',
 'Bedford Stuyvesant - Crown Heights',
 'Downtown - Heights - Slope',
 'Greenpoint',
 'East Flatbush - Flatbush',
 'Canarsie - Flatlands',
 'Bensonhurst - Bay Ridge',
 'Pelham - Throgs Neck',
 'Fordham - Bronx Pk',
 'Northeast Bronx',
 'Kingsbridge - Riverdale',
 'Flushing - Clearview',
 'Borough Park',
 'Coney Island - Sheepshead Bay',
 'Ridgewood - Forest Hills',
 'Williamsburg - Bushwick',
 'Southwest Queens',
 'Jamaica',
 'Southeast Queens',
 'Rockaways',
 'Washington Heights',
 'Central Harlem - Morningside Heights',
 'East Harlem',
 'Upper West Side',
 'Sunset Park',
 'South Beach - Tottenville',
 'Union Square - Lower East Side',
 'Lower Manhattan',
 'Gramercy Park - Murray Hill',
 'Bayside - Little Neck',
 'Fresh Meadows',
 'Port Richmond',
 'Stapleton - St. George',
 'Willowbrook',
 'New York City',
 'Greenwich Village - SoHo',
 'Chelsea - Clinton',
 'Hunts Point - Mott Haven',
 'High Bridge - Morrisania',
 'Crotona -Tremont',
 'Upper East Side',
 'Staten Island',
 'Queens',
 'Manhattan',
 'Bronx',
 'Brooklyn',
 'East Flatbush (CD17)',
 'Woodside and Sunnyside (CD2)',
 'Long Island City and Astoria (CD1)',
 'Flatlands and Canarsie (CD18)',
 'Hunts Point and Longwood (CD2)',
 'Brownsville (CD16)',
 'Jackson Heights (CD3)',
 'Flatbush and Midwood (CD14)',
 'Borough Park (CD12)',
 'Bay Ridge and Dyker Heights (CD10)',
 'South Crown Heights and Lefferts Gardens (CD9)',
 'Fordham and University Heights (CD5)',
 'Highbridge and Concourse (CD4)',
 'Sheepshead Bay (CD15)',
 'Tottenville and Great Kills (CD3)',
 'Elmhurst and Corona (CD4)',
 'South Beach and Willowbrook (CD2)',
 'St. George and Stapleton (CD1)',
 'Rockaway and Broad Channel (CD14)',
 'Queens Village (CD13)',
 'Jamaica and Hollis (CD12)',
 'Bayside and Little Neck (CD11)',
 'Ridgewood and Maspeth (CD5)',
 'South Ozone Park and Howard Beach (CD10)',
 'Kew Gardens and Woodhaven (CD9)',
 'Hillcrest and Fresh Meadows (CD8)',
 'Flushing and Whitestone (CD7)',
 'Rego Park and Forest Hills (CD6)',
 'Morrisania and Crotona (CD3)',
 'Coney Island (CD13)',
 'Mott Haven and Melrose (CD1)',
 'Parkchester and Soundview (CD9)',
 'Morris Park and Bronxdale (CD11)',
 'Williamsbridge and Baychester (CD12)',
 'Greenpoint and Williamsburg (CD1)',
 'Fort Greene and Brooklyn Heights (CD2)',
 'Bedford Stuyvesant (CD3)',
 'Bushwick (CD4)',
 'East New York and Starrett City (CD5)',
 'Park Slope and Carroll Gardens (CD6)',
 'Sunset Park (CD7)',
 'Crown Heights and Prospect Heights (CD8)',
 'Washington Heights and Inwood (CD12)',
 'Kingsbridge Heights and Bedford (CD7)',
 'Riverdale and Fieldston (CD8)',
 'Belmont and East Tremont (CD6)',
 'Bensonhurst (CD11)',
 'Stuyvesant Town and Turtle Bay (CD6)',
 'East Harlem (CD11)',
 'Central Harlem (CD10)',
 'Throgs Neck and Co-op City (CD10)',
 'Upper East Side (CD8)',
 'Upper West Side (CD7)',
 'Morningside Heights and Hamilton Heights (CD9)',
 'Midtown (CD5)',
 'Clinton and Chelsea (CD4)',
 'Lower East Side and Chinatown (CD3)',
 'Greenwich Village and Soho (CD2)',
 'Financial District (CD1)',
 'Upper East Side-Gramercy',
 'Chelsea-Village',
 'Union Square-Lower Manhattan',
 'Bayside Little Neck-Fresh Meadows',
 'Northern SI',
 'Southern SI',
 'South Bronx']

In [14]:
# Se exporta dataset

df_final.to_parquet("df_final.parquet",index=False)     #dataframe 1